"""Genera el HTML con los datos exactos que el sistema muestra."""
import sys
sys.path.insert(0, ".")

from src.utils.programacion_print import generar_html_programacion

# Datos exactos del usuario (copiados del sistema)
lineas = [
    # Segmento 1: tallas 15-21.5
    {"cliente": "LORENZO RUBIO", "folio_prog": "999", "folio_pedido": "",
     "modelo": "9201", "piel": "CRAZY", "color": "CAMEL/CAFÉ",
     "fecha_prog": "2026-08-03", "total_pares": 51,
     "tallas": [
         {"talla": "15", "pares": 4}, {"talla": "15.5", "pares": 4},
         {"talla": "16", "pares": 4}, {"talla": "16.5", "pares": 4},
         {"talla": "17", "pares": 4}, {"talla": "18", "pares": 4},
         {"talla": "18.5", "pares": 4}, {"talla": "19", "pares": 4},
         {"talla": "19.5", "pares": 4}, {"talla": "20", "pares": 4},
         {"talla": "20.5", "pares": 2}, {"talla": "21", "pares": 5},
         {"talla": "21.5", "pares": 4}]},
    {"cliente": "LORENZO RUBIO", "folio_prog": "874", "folio_pedido": "",
     "modelo": "9210", "piel": "CRAZY", "color": "CAMEL/CAMEL",
     "fecha_prog": "2026-08-03", "total_pares": 53,
     "tallas": [
         {"talla": "15", "pares": 4}, {"talla": "15.5", "pares": 4},
         {"talla": "16", "pares": 1}, {"talla": "16.5", "pares": 4},
         {"talla": "17", "pares": 4}, {"talla": "17.5", "pares": 3},
         {"talla": "18", "pares": 4}, {"talla": "18.5", "pares": 4},
         {"talla": "19", "pares": 4}, {"talla": "19.5", "pares": 4},
         {"talla": "20", "pares": 4}, {"talla": "20.5", "pares": 4},
         {"talla": "21", "pares": 3}, {"talla": "21.5", "pares": 6}]},
    {"cliente": "LORENZO RUBIO", "folio_prog": "875", "folio_pedido": "",
     "modelo": "9205", "piel": "CRAZY", "color": "CAMEL/CAFÉ",
     "fecha_prog": "2026-08-03", "total_pares": 29,
     "tallas": [
         {"talla": "15.5", "pares": 4}, {"talla": "16", "pares": 3},
         {"talla": "16.5", "pares": 2}, {"talla": "17", "pares": 1},
         {"talla": "17.5", "pares": 1}, {"talla": "18", "pares": 4},
         {"talla": "18.5", "pares": 3}, {"talla": "19", "pares": 2},
         {"talla": "19.5", "pares": 4}, {"talla": "20", "pares": 4},
         {"talla": "20.5", "pares": 1}]},
    {"cliente": "LORENZO RUBIO", "folio_prog": "876", "folio_pedido": "",
     "modelo": "9248", "piel": "PULL UP", "color": "SHEDRON/AZUL",
     "fecha_prog": "2026-08-03", "total_pares": 60,
     "tallas": [
         {"talla": "15", "pares": 4}, {"talla": "15.5", "pares": 4},
         {"talla": "16", "pares": 4}, {"talla": "16.5", "pares": 4},
         {"talla": "17", "pares": 4}, {"talla": "17.5", "pares": 4},
         {"talla": "18", "pares": 4}, {"talla": "18.5", "pares": 4},
         {"talla": "19", "pares": 4}, {"talla": "19.5", "pares": 4},
         {"talla": "20", "pares": 4}, {"talla": "20.5", "pares": 4},
         {"talla": "21", "pares": 6}, {"talla": "21.5", "pares": 6}]},
    {"cliente": "LORENZO RUBIO", "folio_prog": "877", "folio_pedido": "",
     "modelo": "9257", "piel": "CRAZY", "color": "CAFÉ/CAMEL",
     "fecha_prog": "2026-08-03", "total_pares": 60,
     "tallas": [
         {"talla": "15", "pares": 4}, {"talla": "15.5", "pares": 4},
         {"talla": "16", "pares": 4}, {"talla": "16.5", "pares": 4},
         {"talla": "17", "pares": 4}, {"talla": "17.5", "pares": 4},
         {"talla": "18", "pares": 4}, {"talla": "18.5", "pares": 4},
         {"talla": "19", "pares": 4}, {"talla": "19.5", "pares": 4},
         {"talla": "20", "pares": 4}, {"talla": "20.5", "pares": 4},
         {"talla": "21", "pares": 6}, {"talla": "21.5", "pares": 6}]},
    {"cliente": "LORENZO RUBIO", "folio_prog": "878", "folio_pedido": "",
     "modelo": "9219", "piel": "CRAZY", "color": "CAMEL/CAMEL",
     "fecha_prog": "2026-08-03", "total_pares": 60,
     "tallas": [
         {"talla": "15", "pares": 4}, {"talla": "15.5", "pares": 4},
         {"talla": "16", "pares": 4}, {"talla": "16.5", "pares": 4},
         {"talla": "17", "pares": 4}, {"talla": "17.5", "pares": 4},
         {"talla": "18", "pares": 4}, {"talla": "18.5", "pares": 4},
         {"talla": "19", "pares": 4}, {"talla": "19.5", "pares": 4},
         {"talla": "20", "pares": 4}, {"talla": "20.5", "pares": 4},
         {"talla": "21", "pares": 6}, {"talla": "21.5", "pares": 6}]},
    {"cliente": "CARMELO LOPEZ", "folio_prog": "879", "folio_pedido": "",
     "modelo": "9220", "piel": "CRAZY", "color": "CAFÉ/CAFÉ",
     "fecha_prog": "2026-08-05", "total_pares": 60,
     "tallas": [
         {"talla": "15", "pares": 6}, {"talla": "16", "pares": 6},
         {"talla": "17", "pares": 6}, {"talla": "18", "pares": 10},
         {"talla": "19", "pares": 10}, {"talla": "20", "pares": 10},
         {"talla": "21", "pares": 12}]},
    {"cliente": "CARMELO LOPEZ", "folio_prog": "880", "folio_pedido": "",
     "modelo": "9201", "piel": "CRAZY", "color": "CAFÉ/CAFÉ",
     "fecha_prog": "2026-08-05", "total_pares": 60,
     "tallas": [
         {"talla": "15", "pares": 6}, {"talla": "16", "pares": 6},
         {"talla": "17", "pares": 6}, {"talla": "18", "pares": 10},
         {"talla": "19", "pares": 10}, {"talla": "20", "pares": 10},
         {"talla": "21", "pares": 12}]},
    {"cliente": "CARMELO LOPEZ", "folio_prog": "881", "folio_pedido": "",
     "modelo": "9219", "piel": "CRAZY", "color": "CAMEL/CAMEL",
     "fecha_prog": "2026-08-05", "total_pares": 60,
     "tallas": [
         {"talla": "15", "pares": 6}, {"talla": "16", "pares": 6},
         {"talla": "17", "pares": 6}, {"talla": "18", "pares": 10},
         {"talla": "19", "pares": 10}, {"talla": "20", "pares": 10},
         {"talla": "21", "pares": 12}]},
    {"cliente": "CARMELO LOPEZ", "folio_prog": "882", "folio_pedido": "",
     "modelo": "9201", "piel": "CRAZY", "color": "CAMEL/CAMEL",
     "fecha_prog": "2026-08-05", "total_pares": 60,
     "tallas": [
         {"talla": "15", "pares": 6}, {"talla": "16", "pares": 6},
         {"talla": "17", "pares": 6}, {"talla": "18", "pares": 10},
         {"talla": "19", "pares": 10}, {"talla": "20", "pares": 10},
         {"talla": "21", "pares": 12}]},
    {"cliente": "MARIANA ALCON", "folio_prog": "883", "folio_pedido": "",
     "modelo": "9280", "piel": "CERA", "color": "CAFÉ/CAFÉ",
     "fecha_prog": "2026-08-05", "total_pares": 15,
     "tallas": [
         {"talla": "15", "pares": 1}, {"talla": "15.5", "pares": 1},
         {"talla": "16", "pares": 1}, {"talla": "16.5", "pares": 1},
         {"talla": "17", "pares": 2}, {"talla": "17.5", "pares": 1},
         {"talla": "18", "pares": 1}, {"talla": "18.5", "pares": 1},
         {"talla": "19", "pares": 1}, {"talla": "19.5", "pares": 1},
         {"talla": "20", "pares": 1}, {"talla": "20.5", "pares": 1},
         {"talla": "21", "pares": 1}, {"talla": "21.5", "pares": 1}]},
    {"cliente": "BODEGA", "folio_prog": "885", "folio_pedido": "",
     "modelo": "9213", "piel": "GRABADO PITON", "color": "NEGRO/NEGRO",
     "fecha_prog": "2026-08-06", "total_pares": 24,
     "tallas": [
         {"talla": "15", "pares": 2}, {"talla": "15.5", "pares": 2},
         {"talla": "16", "pares": 2}, {"talla": "16.5", "pares": 2},
         {"talla": "17", "pares": 2}, {"talla": "17.5", "pares": 2},
         {"talla": "18", "pares": 2}, {"talla": "18.5", "pares": 1},
         {"talla": "19", "pares": 2}, {"talla": "19.5", "pares": 1},
         {"talla": "20", "pares": 2}, {"talla": "20.5", "pares": 1},
         {"talla": "21", "pares": 2}, {"talla": "21.5", "pares": 1}]},
    {"cliente": "BODEGA", "folio_prog": "886", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO PITON", "color": "CAFÉ/CAFÉ",
     "fecha_prog": "2026-08-06", "total_pares": 24,
     "tallas": [
         {"talla": "15", "pares": 2}, {"talla": "15.5", "pares": 2},
         {"talla": "16", "pares": 2}, {"talla": "16.5", "pares": 2},
         {"talla": "17", "pares": 2}, {"talla": "17.5", "pares": 2},
         {"talla": "18", "pares": 2}, {"talla": "18.5", "pares": 1},
         {"talla": "19", "pares": 2}, {"talla": "19.5", "pares": 1},
         {"talla": "20", "pares": 2}, {"talla": "20.5", "pares": 1},
         {"talla": "21", "pares": 2}, {"talla": "21.5", "pares": 1}]},
    {"cliente": "BODEGA", "folio_prog": "887", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO PITON", "color": "CAMEL/CAMEL",
     "fecha_prog": "2026-08-06", "total_pares": 24,
     "tallas": [
         {"talla": "15", "pares": 2}, {"talla": "15.5", "pares": 2},
         {"talla": "16", "pares": 2}, {"talla": "16.5", "pares": 2},
         {"talla": "17", "pares": 2}, {"talla": "17.5", "pares": 2},
         {"talla": "18", "pares": 2}, {"talla": "18.5", "pares": 1},
         {"talla": "19", "pares": 2}, {"talla": "19.5", "pares": 1},
         {"talla": "20", "pares": 2}, {"talla": "20.5", "pares": 1},
         {"talla": "21", "pares": 2}, {"talla": "21.5", "pares": 1}]},
    {"cliente": "BODEGA", "folio_prog": "888", "folio_pedido": "",
     "modelo": "9213", "piel": "GRABADO NUCA", "color": "NEGRO/NEGRO",
     "fecha_prog": "2026-08-06", "total_pares": 24,
     "tallas": [
         {"talla": "15", "pares": 2}, {"talla": "15.5", "pares": 2},
         {"talla": "16", "pares": 2}, {"talla": "16.5", "pares": 2},
         {"talla": "17", "pares": 2}, {"talla": "17.5", "pares": 2},
         {"talla": "18", "pares": 2}, {"talla": "18.5", "pares": 1},
         {"talla": "19", "pares": 2}, {"talla": "19.5", "pares": 1},
         {"talla": "20", "pares": 2}, {"talla": "20.5", "pares": 1},
         {"talla": "21", "pares": 2}, {"talla": "21.5", "pares": 1}]},
    {"cliente": "BODEGA", "folio_prog": "889", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO NUCA", "color": "CAFÉ/CAFÉ",
     "fecha_prog": "2026-08-06", "total_pares": 24,
     "tallas": [
         {"talla": "15", "pares": 2}, {"talla": "15.5", "pares": 2},
         {"talla": "16", "pares": 2}, {"talla": "16.5", "pares": 2},
         {"talla": "17", "pares": 2}, {"talla": "17.5", "pares": 2},
         {"talla": "18", "pares": 2}, {"talla": "18.5", "pares": 1},
         {"talla": "19", "pares": 2}, {"talla": "19.5", "pares": 1},
         {"talla": "20", "pares": 2}, {"talla": "20.5", "pares": 1},
         {"talla": "21", "pares": 2}, {"talla": "21.5", "pares": 1}]},
    {"cliente": "BODEGA", "folio_prog": "872", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO NUCA", "color": "CAMEL/CAMEL",
     "fecha_prog": "2026-08-07", "total_pares": 24,
     "tallas": [
         {"talla": "15", "pares": 2}, {"talla": "15.5", "pares": 2},
         {"talla": "16", "pares": 2}, {"talla": "16.5", "pares": 2},
         {"talla": "17", "pares": 2}, {"talla": "17.5", "pares": 2},
         {"talla": "18", "pares": 2}, {"talla": "18.5", "pares": 1},
         {"talla": "19", "pares": 2}, {"talla": "19.5", "pares": 1},
         {"talla": "20", "pares": 2}, {"talla": "20.5", "pares": 1},
         {"talla": "21", "pares": 2}, {"talla": "21.5", "pares": 1}]},
    # Segmento 2: tallas 22-26
    {"cliente": "CACILLAS", "folio_prog": "871", "folio_pedido": "980",
     "modelo": "2402", "piel": "CERA", "color": "CAFÉ /CAFÉ",
     "fecha_prog": "", "total_pares": 52,
     "tallas": [
         {"talla": "22", "pares": 4}, {"talla": "22", "pares": 4},
         {"talla": "23", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "24", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "25", "pares": 2}]},
    {"cliente": "MARIANA ALCON", "folio_prog": "884", "folio_pedido": "",
     "modelo": "9280", "piel": "CERA", "color": "CAFÉ/CAFÉ",
     "fecha_prog": "", "total_pares": 14,
     "tallas": [
         {"talla": "22", "pares": 1}, {"talla": "22", "pares": 1},
         {"talla": "23", "pares": 1}, {"talla": "24", "pares": 1},
         {"talla": "24", "pares": 1}, {"talla": "24", "pares": 1},
         {"talla": "25", "pares": 1}]},
    {"cliente": "BODEGA", "folio_prog": "895", "folio_pedido": "",
     "modelo": "9213", "piel": "GRABADO PITON", "color": "NEGRO/NEGRO",
     "fecha_prog": "", "total_pares": 48,
     "tallas": [
         {"talla": "22", "pares": 2}, {"talla": "22", "pares": 2},
         {"talla": "23", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "24", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "25", "pares": 4}]},
    {"cliente": "BODEGA", "folio_prog": "896", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO PITON", "color": "CAFÉ/CAFÉ",
     "fecha_prog": "", "total_pares": 48,
     "tallas": [
         {"talla": "22", "pares": 2}, {"talla": "22", "pares": 2},
         {"talla": "23", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "24", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "25", "pares": 4}]},
    {"cliente": "BODEGA", "folio_prog": "897", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO PITON", "color": "CAMEL/CAMEL",
     "fecha_prog": "", "total_pares": 48,
     "tallas": [
         {"talla": "22", "pares": 2}, {"talla": "22", "pares": 2},
         {"talla": "23", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "24", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "25", "pares": 4}]},
    {"cliente": "BODEGA", "folio_prog": "898", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO NUCA", "color": "NEGRO/NEGRO",
     "fecha_prog": "", "total_pares": 48,
     "tallas": [
         {"talla": "22", "pares": 2}, {"talla": "22", "pares": 2},
         {"talla": "23", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "24", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "25", "pares": 4}]},
    {"cliente": "BODEGA", "folio_prog": "899", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO NUCA", "color": "CAFÉ/CAFÉ",
     "fecha_prog": "", "total_pares": 48,
     "tallas": [
         {"talla": "22", "pares": 2}, {"talla": "22", "pares": 2},
         {"talla": "23", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "24", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "25", "pares": 4}]},
    {"cliente": "BODEGA", "folio_prog": "900", "folio_pedido": "",
     "modelo": "9240", "piel": "GRABADO NUCA", "color": "CAMEL/CAMEL",
     "fecha_prog": "", "total_pares": 48,
     "tallas": [
         {"talla": "22", "pares": 2}, {"talla": "22", "pares": 2},
         {"talla": "23", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "24", "pares": 4}, {"talla": "24", "pares": 4},
         {"talla": "25", "pares": 4}]},
]

titulo = "PROGRAMACIÓN SEMANAL — 03-07 agosto 2026"
html = generar_html_programacion(lineas, titulo=titulo, incluir_semana=False,
                                 auto_imprimir=False)

from pathlib import Path
ruta = Path("reporte_real_03_07_agosto.html")
ruta.write_text(html, encoding="utf-8")
print(f"HTML guardado en: {ruta.resolve()}")
